#C1 W6.2
#get facebook and github client id and secret from the respective sites/developer account
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 876348765-sdjhfgshjdaglsgkjfg.apps.googleusercontent.com
            client-secret: GJCSDKJB-M0kjsdgbjkGJd56_L_RDMkjbsdkGYsb
          github:
            client-id: 1b3b1b3b1b3b1b3b1b3b
            client-secret: 1b3b
          facebook:
            client-id: 1b3b1b3b1b3b1b3b1b3b
            client-secret: 1b3b

